### ISSUE TITLE
is it possible to do yield buffers with this library?

### ISSUE THREAD

**Issue by AKST** [mciparelli/co-redis#14]
According to the [docs for the vanilla redis][1] client this will yield a buffer to the callback
```
client.get(new Buffer("foo_rand000000000000"), function (err, reply) {
    console.log(reply.toString());
});
```

But when I try this in coredis I get typeof string

```
 console.log(typeof (yield client.get(new Buffer("foo_rand000000000000"))));
```

On top of that it's even slower than the string when you just do this

```
 console.log(typeof (yield client.get("foo_rand000000000000")));
``` 

[1]: https://www.npmjs.com/package/redis#clientauthpassword-callback

**Comment by mciparelli** [comment]
https://github.com/mciparelli/co-redis/commit/e276ef41479a2968b55e4f9f3e5225480ec12718

**Comment by AKST** [comment]
oh cool, I'll close the issue then
