### ISSUE TITLE
Redis 2.6.0 broke this module

### ISSUE THREAD

**Issue by LinusU** [mciparelli/co-redis#16]
https://github.com/NodeRedis/node_redis/commit/ffaaf0f6d5311326f9a1f8f6c6a3fd7d060a0b44

This commit broke this module since thenify is using the function name inside an eval statement. Since the name of one function is now `restore-asking` if fails with a syntax error :(

**Comment by LinusU** [comment]
Also reported here: NodeRedis/node_redis

**Comment by mciparelli** [comment]
Was this fixed in node_redis already? Is there anything we could do about it to fix this or it's more like a thenify thing?

**Comment by LinusU** [comment]
I don't think that there is anything that needs to be done here since it's fixed upstream, closing...
