### ISSUE TITLE
Can't catch co-redis.get error when the key is missing in redis

### ISSUE THREAD

**Issue by cosmicscr** [mciparelli/co-redis#18]
If co-redis tries to get a key that doesn't exist in the redis db, my Koa web server just sends an internal server error and I cannot catch the error.  Why is it that whatever the error is not propagated to my catch block?

```
            try
            {
                something = yield coRedis.get('nonExistentKey')
            } catch (err)
            {
                console.log(err); // I never get here, my koa server just throws internal server error
            }
```

**Comment by mciparelli** [comment]
Citing node_redis docs:

> If the key is missing, reply will be null. Only if the Redis Command Reference states something else it will not be null.

So in your case `something` should be `null`, no error thrown by this lib with that code. Are you sure the error isn't triggered somewhere else?

**Comment by mciparelli** [comment]
Closed due to inactivity
