### ISSUE TITLE
Proper way to reconnect to redis

### ISSUE THREAD

**Issue by amit777** [mciparelli/co-redis#9]
Does the example in the README use a persistent connection to redis? If so, is there a best practice way to reconnect?  Like listening to an error event.  Or does each request to redis create a new connection?

**Comment by juliangruber** [comment]
that is all taken care of by [node-redis](https://github.com/mranney/node_redis), this library is merely a wrapper around it. it uses a persistent connection and tries to reconnect, see https://github.com/mranney/node_redis#rediscreateclient
